name: ar_study_cards
description: A Flutter app for AR flashcards to help students study.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  ar_flutter_plugin: ^0.7.3
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.68.0
  flip_card: ^0.7.0
  csv: ^6.0.0
  file_picker: ^8.0.0
  staggered_grid_view_flutter: ^0.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/models/flashcard.glb